"""Mock LLM backend for testing the RAG pipeline without an API key."""

from src.llm.base import BaseLLM


class MockLLM(BaseLLM):
    """A deterministic mock LLM backend."""

    def __init__(self, answer_language: str = "zh") -> None:
        """Initialize mock backend with a response language."""
        language = (answer_language or "zh").strip().lower()
        self.answer_language = "en" if language in {"en", "english", "英文"} else "zh"

    def generate(self, prompt: str) -> str:
        """Return a template answer for pipeline testing."""
        if self.answer_language == "en":
            return "\n".join(
                [
                    "Answer:",
                    "This is a mock answer. The RAG pipeline has successfully retrieved evidence and built a prompt.",
                    "",
                    "Supporting pages:",
                    "Please check the retrieved evidence pages.",
                    "",
                    "Reasoning:",
                    "The real answer should be generated by qwen3-vl-flash or another LLM backend.",
                ]
            )

        return "\n".join(
            [
                "回答：",
                "这是一个 Mock 答案。RAG 流程已经成功完成证据检索和中文提示词构建。",
                "",
                "支持页码：",
                "请查看检索证据中显示的页码。",
                "",
                "推理：",
                "真实答案应由 qwen3-vl-flash 或其他大模型后端根据检索证据生成。",
            ]
        )
