"""Build embedding vectors and FAISS indexes for paper chunks."""

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

import faiss
import numpy as np
from sentence_transformers import SentenceTransformer


DEFAULT_EMBEDDING_MODEL = "BAAI/bge-small-en-v1.5"


def load_chunks(chunks_path: str) -> dict[str, Any]:
    """Load a chunk JSON file generated by ``run_chunk_text.py``.

    Args:
        chunks_path: Path to the chunks JSON file.

    Returns:
        Loaded chunk data.

    Raises:
        FileNotFoundError: If the chunks file does not exist.
        ValueError: If the JSON structure is invalid.
    """
    path = Path(chunks_path)
    if not path.exists():
        raise FileNotFoundError(f"Chunks JSON not found: {path}")
    if not path.is_file():
        raise ValueError(f"Chunks path is not a file: {path}")

    try:
        with path.open("r", encoding="utf-8") as file:
            chunks_data = json.load(file)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid chunks JSON file: {path}") from exc
    except Exception as exc:
        raise RuntimeError(f"Failed to load chunks JSON: {path}") from exc

    if not isinstance(chunks_data, dict):
        raise ValueError("Chunks JSON must contain an object.")
    if "chunks" not in chunks_data or not isinstance(chunks_data["chunks"], list):
        raise ValueError("Chunks JSON must contain a list field named 'chunks'.")

    return chunks_data


@lru_cache(maxsize=4)
def load_embedding_model(model_name: str = DEFAULT_EMBEDDING_MODEL) -> SentenceTransformer:
    """Load a SentenceTransformer embedding model."""
    try:
        return SentenceTransformer(model_name)
    except Exception as exc:
        message = f"Failed to load embedding model: {model_name}"
        if model_name == DEFAULT_EMBEDDING_MODEL:
            message += (
                "\nThis may be caused by Hugging Face model download failure."
                "\nOn Windows PowerShell, you can try:"
                '\n  $env:HF_ENDPOINT="https://hf-mirror.com"'
                '\n  $env:HF_HOME="$PWD\\.hf_cache"'
                "\nThen run:"
                "\n  python scripts/test_bge_download.py"
                "\nIf the test downloads a local fallback model, use:"
                "\n  --model-name models\\bge-small-en-v1.5-hf-mirror"
                "\nAlternatively, consider using a qwen-api embedding backend or text-embedding-v4."
            )
        raise RuntimeError(message) from exc


def encode_chunks(
    model: SentenceTransformer,
    chunks: list[dict[str, Any]],
    batch_size: int = 32,
) -> np.ndarray:
    """Encode chunk texts into normalized embedding vectors.

    Args:
        model: Loaded SentenceTransformer model.
        chunks: Chunk metadata dictionaries.
        batch_size: Encoding batch size.

    Returns:
        A float32 numpy array with shape ``(num_chunks, embedding_dim)``.
    """
    if batch_size <= 0:
        raise ValueError("batch_size must be greater than 0.")
    if not chunks:
        raise ValueError("Cannot encode an empty chunk list.")

    texts = [str(chunk.get("text", "") or "") for chunk in chunks]
    try:
        embeddings = model.encode(
            texts,
            convert_to_numpy=True,
            show_progress_bar=True,
            batch_size=batch_size,
            normalize_embeddings=True,
        )
    except Exception as exc:
        raise RuntimeError("Failed to encode chunk texts.") from exc

    embeddings = np.asarray(embeddings, dtype=np.float32)
    if embeddings.ndim != 2:
        raise ValueError(f"Expected 2D embeddings, got shape {embeddings.shape}.")

    return embeddings


def build_faiss_index(embeddings: np.ndarray) -> faiss.IndexFlatIP:
    """Build a FAISS inner-product index from normalized embeddings."""
    if embeddings.ndim != 2:
        raise ValueError(f"Expected 2D embeddings, got shape {embeddings.shape}.")
    if embeddings.shape[0] == 0:
        raise ValueError("Cannot build FAISS index from empty embeddings.")

    embeddings = np.asarray(embeddings, dtype=np.float32)
    embedding_dim = embeddings.shape[1]
    index = faiss.IndexFlatIP(embedding_dim)
    index.add(embeddings)
    return index


def save_faiss_index(index: faiss.Index, output_path: str) -> Path:
    """Save a FAISS index to disk."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    try:
        faiss.write_index(index, str(path))
    except Exception as exc:
        raise RuntimeError(f"Failed to save FAISS index: {path}") from exc

    return path


def save_metadata(chunks_data: dict[str, Any], output_path: str) -> Path:
    """Save chunk metadata without embeddings."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    metadata = {
        "paper_id": chunks_data.get("paper_id", ""),
        "pdf_name": chunks_data.get("pdf_name", ""),
        "num_chunks": len(chunks_data.get("chunks", [])),
        "chunks": chunks_data.get("chunks", []),
    }

    try:
        with path.open("w", encoding="utf-8") as file:
            json.dump(metadata, file, ensure_ascii=False, indent=2)
    except Exception as exc:
        raise RuntimeError(f"Failed to save metadata JSON: {path}") from exc

    return path


def build_index_from_chunks(
    chunks_path: str,
    output_dir: str = "data/extracted/faiss_index",
    model_name: str = DEFAULT_EMBEDDING_MODEL,
    batch_size: int = 32,
) -> dict[str, Any]:
    """Build and save a FAISS index from a chunks JSON file."""
    chunks_data = load_chunks(chunks_path)
    paper_id = str(chunks_data.get("paper_id", "")).strip()
    pdf_name = str(chunks_data.get("pdf_name", "")).strip()
    chunks = chunks_data["chunks"]

    if not paper_id:
        raise ValueError("Chunks data is missing paper_id.")
    if not pdf_name:
        raise ValueError("Chunks data is missing pdf_name.")
    if not chunks:
        raise ValueError("Chunks data contains no chunks.")

    model = load_embedding_model(model_name)
    embeddings = encode_chunks(model, chunks, batch_size=batch_size)
    index = build_faiss_index(embeddings)

    output_root = Path(output_dir)
    index_path = output_root / f"{paper_id}.index"
    metadata_path = output_root / f"{paper_id}_metadata.json"

    save_faiss_index(index, str(index_path))
    save_metadata(chunks_data, str(metadata_path))

    return {
        "paper_id": paper_id,
        "pdf_name": pdf_name,
        "num_chunks": len(chunks),
        "embedding_dim": int(embeddings.shape[1]),
        "index_path": index_path.as_posix(),
        "metadata_path": metadata_path.as_posix(),
    }
