"""Text chunking helpers for parsed paper JSON files."""

import json
from pathlib import Path
from typing import Any


def load_parsed_pdf(json_path: str) -> dict[str, Any]:
    """Load a parsed PDF JSON file.

    Args:
        json_path: Path to the JSON file generated by ``parse_pdf.py``.

    Returns:
        Parsed PDF data.

    Raises:
        FileNotFoundError: If the JSON file does not exist.
        ValueError: If the JSON content is not a dictionary.
        RuntimeError: If JSON loading fails.
    """
    path = Path(json_path)
    if not path.exists():
        raise FileNotFoundError(f"Parsed PDF JSON not found: {path}")
    if not path.is_file():
        raise ValueError(f"Parsed PDF JSON path is not a file: {path}")

    try:
        with path.open("r", encoding="utf-8") as file:
            data = json.load(file)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON file: {path}") from exc
    except Exception as exc:
        raise RuntimeError(f"Failed to load parsed PDF JSON: {path}") from exc

    if not isinstance(data, dict):
        raise ValueError(f"Parsed PDF JSON must contain an object: {path}")

    return data


def split_text_by_chars(
    text: str,
    chunk_size: int = 800,
    chunk_overlap: int = 150,
) -> list[dict[str, Any]]:
    """Split text into overlapping character chunks.

    Args:
        text: Input text.
        chunk_size: Maximum number of characters per chunk.
        chunk_overlap: Number of overlapping characters between chunks.

    Returns:
        A list of chunk dictionaries with text and character offsets.

    Raises:
        ValueError: If chunk parameters are invalid.
    """
    if chunk_size <= 0:
        raise ValueError("chunk_size must be greater than 0.")
    if chunk_overlap < 0:
        raise ValueError("chunk_overlap must be greater than or equal to 0.")
    if chunk_overlap >= chunk_size:
        raise ValueError("chunk_overlap must be smaller than chunk_size.")

    if not text:
        return []

    chunks: list[dict[str, Any]] = []
    text_length = len(text)
    start = 0
    step = chunk_size - chunk_overlap

    while start < text_length:
        end = min(start + chunk_size, text_length)
        chunk_text = text[start:end]
        chunks.append(
            {
                "text": chunk_text,
                "char_start": start,
                "char_end": end,
            }
        )

        if end >= text_length:
            break
        start += step

    return chunks


def build_chunks(
    parsed_pdf: dict[str, Any],
    chunk_size: int = 800,
    chunk_overlap: int = 150,
) -> dict[str, Any]:
    """Build page-level text chunks from parsed PDF data.

    Args:
        parsed_pdf: Parsed PDF dictionary generated by ``parse_pdf.py``.
        chunk_size: Maximum number of characters per chunk.
        chunk_overlap: Number of overlapping characters between chunks.

    Returns:
        Chunk data ready to be saved as JSON.
    """
    paper_id = str(parsed_pdf.get("paper_id", "")).strip()
    pdf_name = str(parsed_pdf.get("pdf_name", "")).strip()
    pages = parsed_pdf.get("pages", [])

    if not paper_id:
        raise ValueError("parsed_pdf is missing paper_id.")
    if not pdf_name:
        raise ValueError("parsed_pdf is missing pdf_name.")
    if not isinstance(pages, list):
        raise ValueError("parsed_pdf['pages'] must be a list.")

    all_chunks: list[dict[str, Any]] = []
    for page in pages:
        if not isinstance(page, dict):
            raise ValueError("Each page record must be a dictionary.")

        page_id = int(page.get("page_id", 0))
        if page_id <= 0:
            raise ValueError("Each page record must have a positive page_id.")

        page_text = page.get("text", "") or ""
        page_image = page.get("page_image", "")
        page_chunks = split_text_by_chars(
            text=page_text,
            chunk_size=chunk_size,
            chunk_overlap=chunk_overlap,
        )

        for chunk_index, chunk in enumerate(page_chunks, start=1):
            chunk_id = f"{paper_id}_p{page_id:03d}_c{chunk_index:03d}"
            all_chunks.append(
                {
                    "chunk_id": chunk_id,
                    "paper_id": paper_id,
                    "pdf_name": pdf_name,
                    "page_id": page_id,
                    "chunk_index": chunk_index,
                    "text": chunk["text"],
                    "char_start": chunk["char_start"],
                    "char_end": chunk["char_end"],
                    "page_image": page_image,
                }
            )

    return {
        "paper_id": paper_id,
        "pdf_name": pdf_name,
        "num_pages": int(parsed_pdf.get("num_pages", len(pages))),
        "num_chunks": len(all_chunks),
        "chunks": all_chunks,
    }


def save_chunks(chunks_data: dict[str, Any], output_path: str) -> Path:
    """Save chunk data as a UTF-8 JSON file."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    try:
        with path.open("w", encoding="utf-8") as file:
            json.dump(chunks_data, file, ensure_ascii=False, indent=2)
    except Exception as exc:
        raise RuntimeError(f"Failed to save chunks JSON: {path}") from exc

    return path


def chunk_parsed_pdf(
    input_json_path: str,
    output_dir: str = "data/extracted/chunks",
    chunk_size: int = 800,
    chunk_overlap: int = 150,
) -> dict[str, Any]:
    """Load parsed PDF JSON, build chunks, and save the chunk JSON file."""
    parsed_pdf = load_parsed_pdf(input_json_path)
    chunks_data = build_chunks(
        parsed_pdf=parsed_pdf,
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
    )

    paper_id = chunks_data["paper_id"]
    output_path = Path(output_dir) / f"{paper_id}_chunks.json"
    save_chunks(chunks_data, str(output_path))
    return chunks_data
